[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libsqlite3-0 libsqlite3-dev",
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
]

[start]
cmd = "python bot.py"
